pub const SNSES: &[(&str, &str)] = &[
    ("Alice", "oa5dz-haaaa-aaaaq-aaegq-cai"),
    ("Boom DAO", "xomae-vyaaa-aaaaq-aabhq-cai"),
    ("Catalyze", "umz53-fiaaa-aaaaq-aabmq-cai"),
    ("Cecil The Lion DAO", "jt5an-tqaaa-aaaaq-aaevq-cai"),
    ("Cycles Transfer Station", "igbbe-6yaaa-aaaaq-aadnq-cai"),
    ("DecideAI DAO", "xvj4b-paaaa-aaaaq-aabfa-cai"),
    ("DOGMI", "ni4my-zaaaa-aaaaq-aadra-cai"),
    ("DOLR AI", "6wcax-haaaa-aaaaq-aaava-cai"),
    ("Dragginz", "zqfso-syaaa-aaaaq-aaafq-cai"),
    ("ELNA AI", "gdnpl-daaaa-aaaaq-aacna-cai"),
    ("EstateDAO", "bmjwo-aqaaa-aaaaq-aac4a-cai"),
    ("FomoWell", "o3y74-5yaaa-aaaaq-aaeea-cai"),
    ("FuelEV", "nmkto-maaaa-aaaaq-aaemq-cai"),
    ("Gold DAO", "tr3th-kiaaa-aaaaq-aab6q-cai"),
    ("IC Explorer", "icx6s-lyaaa-aaaaq-aaeqa-cai"),
    ("ICFC", "detjl-sqaaa-aaaaq-aacqa-cai"),
    ("ICGhost", "4l7o7-uiaaa-aaaaq-aaa2q-cai"),
    ("ICLighthouse DAO", "hodlf-miaaa-aaaaq-aackq-cai"),
    ("ICPanda", "dwv6s-6aaaa-aaaaq-aacta-cai"),
    ("ICPCC DAO LLC", "lyqgk-ziaaa-aaaaq-aadeq-cai"),
    ("ICPEx", "lseuu-xyaaa-aaaaq-aaeya-cai"),
    ("ICPSwap", "cvzxu-kyaaa-aaaaq-aacvq-cai"),
    ("ICVC", "ntzq5-dyaaa-aaaaq-aadtq-cai"),
    ("Kinic", "74ncn-fqaaa-aaaaq-aaasa-cai"),
    ("KongSwap", "oypg6-faaaa-aaaaq-aadza-cai"),
    ("Motoko", "k34pm-nqaaa-aaaaq-aadca-cai"),
    ("Neutrinite", "eqsml-lyaaa-aaaaq-aacdq-cai"),
    ("NFID Wallet", "mpg2i-yyaaa-aaaaq-aaeka-cai"),
    ("Nuance", "rqch6-oaaaa-aaaaq-aabta-cai"),
    ("OpenChat", "2jvtu-yqaaa-aaaaq-aaama-cai"),
    ("ORIGYN", "lnxxh-yaaaa-aaaaq-aadha-cai"),
    ("Personal DAO", "iqrjl-hiaaa-aaaaq-aaeta-cai"),
    ("Seers", "rceqh-cqaaa-aaaaq-aabqa-cai"),
    ("Sneed", "fi3zi-fyaaa-aaaaq-aachq-cai"),
    ("SONIC", "qgj7v-3qaaa-aaaaq-aabwa-cai"),
    ("TRAX", "elxqo-raaaa-aaaaq-aacba-cai"),
    ("WaterNeuron", "jfnic-kaaaa-aaaaq-aadla-cai"),
    ("Yuku AI", "auadn-oqaaa-aaaaq-aacya-cai"),
];
