[package]
name = "np-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
ring = "0.17.14"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
thiserror = "2.0.12"
toml = "0.7.6"
